name: Get check and decide on next steps

on:
  pull_request:
  pull_request_review:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - run: echo "Hey"

    - id: check-combined
      run: |
        state=$(gh api /repos/${{ github.repository }}/commits/${{ github.sha }}/status -q ".state")

        echo "Check combined state is $state"
        echo "state=$state" >> $GITHUB_OUTPUT
