name: Get check and decide on next steps

on:
  pull_request:
  pull_request_review:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - run: echo "Hey"

    - id: warning
      run: echo "warning=false" >> $GITHUB_OUTPUT

    # Check if PR is in what state by doing combined status check
    - id: check-combined
      run: |
        state=$(gh api /repos/${{ github.repository }}/commits/${{ github.sha }}/status -q ".state")

        echo "Check combined state is $state"
        echo "state=$state" >> $GITHUB_OUTPUT
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # If this is a pull_request event, and warning is True, we ping the team
    # If this is a pull_request_review, we need to check if it is already succeed, if not, still ping the team
    - if: ${{ steps.check-combined.outputs.state != 'success' }}
      run: |
        echo "Runs if PR is not yet in a success state"
    

    
