name: Get check and decide on next steps

on:
  # This runs whenever a PR is opened
  # And PR is being reviewed (someone submits a review)
  pull_request:
  pull_request_review:
  
jobs:
  test-pr:
    name: Test Pull Request
  
    if: ${{ github.event_name == 'pull_request' }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set check required or not in a PR
      id: set
      run: |
        required=$(cat .review)
        echo "required=$required" >> $GITHUB_OUTPUT

    outputs:
      required: ${{ steps.set.outputs.required }}
      
  check-review-status:
    runs-on: ubuntu-latest

    env:
      security_review_context: security-review
      security_team: security-team

    needs:
    - test-pr

    if: |
      always() &&
      needs.test-pr.result == 'success' || needs.test-pr.result == 'skipped'

    name: ${{ github.event_name == 'pull_request' && 'Set' || 'Update' }} Pull Request Status Checks
      
    steps:

    - name: Get GitHub app token
      uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ secrets.LAB_APP_ID }}
        private-key: ${{ secrets.LAB_APP_PRIVATE_KEY }}
        owner: ${{ github.repository_owner }}

    - if: github.event_name == 'pull_request' && needs.test-pr.outputs.required == 'false'
      name: Skip status check if it's not required
      run: |      
          gh api -X POST /repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -f "state=success" \
            -f "description=Skipped required review." \
            -f "context=${{ env.security_review_context }}"
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}

    # DEBUG PR labels
    - if: github.event_name == 'pull_request_review'
      id: pr-labels
      env: 
          PR_LABEL_LIST: ${{ toJson(github.event.pull_request_review.pull_request.labels.*.name) }}
      run: |
        echo $PR_LABEL_LIST
        
    # If this is a pull_request event, and warning is True, we ping the team
    # If this is a pull_request_review, we check if it's labeled, and still ping the team
    # This action will update the status check if the team has already reviewed
    
    - if: |
        (github.event_name == 'pull_request' && needs.test-pr.outputs.required == 'true') ||
        (github.event_name == 'pull_request_review' && contains(github.event.pull_request_review.pull_request.labels.*.name, ${{ env.security_review_context }}))
      name: Ping required team
      uses: Automattic/action-required-review@v4
      with:
        requirements: |
          - paths: unmatched
            teams:
              - ${{ env.security_team }}
        status: ${{ env.security_review_context }}
        request-reviews: true
        token: ${{ steps.app-token.outputs.token }}
