name: Get check and decide on next steps

on:
  pull_request:
  pull_request_review:
  workflow_dispatch:

jobs:
  pr-check:
    if: ${{ github.event_name == 'pull_request' }}

    runs-on: ubuntu-latest

    steps:
    - name: Set check required or not in a PR
      id: set
      run: |
        echo "required=true" >> $GITHUB_OUTPUT

    outputs:
      required: ${{ steps.set.outputs.required }}
      
  check-review-status:
    runs-on: ubuntu-latest

    env:
      # vars.security_review_context
      security_review_context: security-review
      security_team: security-team

    needs:
    - pr-check

    if: |
      always() &&
      needs.pr-check.result == 'success' || needs.pr-check.result == 'skipped'
      
    steps:
    - if: ${{ github.event_name == 'pull_request_review' }}
      name: Check PR check status when someone submits a review
      id: check-combined
      run: |
        state=$(gh api /repos/${{ github.repository }}/commits/${{ github.sha }}/status -q ".state")

        echo "Check combined state is $state"
        echo "state=$state" >> $GITHUB_OUTPUT
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # If this is a pull_request event, and warning is True, we ping the team
    # If this is a pull_request_review, we still need to check if it is still pending and ping the team 
    # This action will update the status check if the team has already reviewed
    - if: |
        (github.event_name == 'pull_request' && needs.pr-check.outputs.required == 'true') ||
        (github.event_name == 'pull_request_review' && steps.check-combined.outputs.state == 'pending')
      name: Ping required team
      uses: Automattic/action-required-review@v4
      with:
        requirements: |
          - paths: unmatched
            teams:
              - ${{ env.security_team }}
        status: ${{ env.security_review_context }}
        request-reviews: true
        token: ${{ secrets.LAB_TOKEN }}
